-- Create sections for MovingWaldo Relocation Specialist - Level 1 Course
INSERT INTO public.sections (course_id, title, description, order_index) VALUES
('686e9880-e7b9-464b-b5b9-d7632e211b0c', 'Foundation & Client Understanding', 'Learn the fundamentals of relocation services and how to understand client needs effectively.', 1),
('686e9880-e7b9-464b-b5b9-d7632e211b0c', 'Planning & Documentation', 'Master the essential planning processes and documentation requirements for successful relocations.', 2),
('686e9880-e7b9-464b-b5b9-d7632e211b0c', 'Communication & Service Excellence', 'Develop exceptional communication skills and service delivery standards.', 3),
('686e9880-e7b9-464b-b5b9-d7632e211b0c', 'Specialized Relocations', 'Handle complex relocation scenarios including corporate and international moves.', 4),
('686e9880-e7b9-464b-b5b9-d7632e211b0c', 'Professional Practice', 'Understand professional ethics, standards, and career development in the relocation industry.', 5);

-- Create subsections for Section 1: Foundation & Client Understanding
INSERT INTO public.subsections (section_id, title, content, video_url, subsection_type, order_index, duration_minutes) VALUES
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 1), 'Introduction to Relocation Services', 'Welcome to your journey as a MovingWaldo Relocation Specialist! In this comprehensive introduction, you''ll discover the exciting world of relocation services and how MovingWaldo is revolutionizing the moving industry. We''ll explore the core principles that make our service exceptional and how you can become an integral part of helping families and individuals navigate one of life''s most significant transitions.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'content', 1, 15),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 1), 'Understanding Client Needs', 'Every relocation is unique, and understanding your client''s specific needs is crucial for success. This module teaches you how to conduct effective client consultations, identify key concerns and priorities, and develop customized solutions. You''ll learn active listening techniques, needs assessment frameworks, and how to build trust from the first interaction.', NULL, 'content', 2, 20),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 1), 'Building Client Relationships', 'Strong client relationships are the foundation of successful relocations. Learn proven strategies for establishing rapport, maintaining communication throughout the process, and creating lasting partnerships. This module covers relationship-building techniques, client retention strategies, and how to turn satisfied clients into advocates for your services.', NULL, 'content', 3, 18),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 1), 'Foundation Knowledge Assessment', 'Test your understanding of the fundamental concepts covered in this section.', NULL, 'quiz', 4, 10);

-- Create subsections for Section 2: Planning & Documentation
INSERT INTO public.subsections (section_id, title, content, video_url, subsection_type, order_index, duration_minutes) VALUES
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 2), 'Creating Relocation Timelines', 'Master the art of timeline creation for successful relocations. This comprehensive guide covers how to develop realistic timelines, account for potential delays, and coordinate multiple moving parts. You''ll learn to balance client expectations with practical constraints and create schedules that ensure smooth, stress-free relocations.', NULL, 'content', 1, 25),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 2), 'Essential Documentation', 'Navigate the complex world of relocation documentation with confidence. This module covers all the essential paperwork, permits, and legal documents required for different types of moves. Learn how to prepare, organize, and manage documentation to ensure compliance and avoid delays.', NULL, 'content', 2, 22),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 2), 'Legal Requirements & Compliance', 'Understand the legal landscape of relocation services including licensing requirements, insurance obligations, and regulatory compliance. This critical module ensures you operate within legal boundaries while protecting both your clients and your business.', NULL, 'content', 3, 20),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 2), 'Planning & Documentation Assessment', 'Evaluate your knowledge of planning processes and documentation requirements.', NULL, 'quiz', 4, 15);

-- Create subsections for Section 3: Communication & Service Excellence
INSERT INTO public.subsections (section_id, title, content, video_url, subsection_type, order_index, duration_minutes) VALUES
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 3), 'Communication Best Practices', 'Excellence in communication sets great relocation specialists apart. Learn proven techniques for clear, effective communication across all channels. This module covers verbal and written communication skills, cultural sensitivity, and how to adapt your communication style to different client personalities and situations.', NULL, 'content', 1, 18),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 3), 'Managing Difficult Situations', 'Every relocation specialist will encounter challenging situations. Learn how to handle delays, complications, difficult clients, and unexpected problems with professionalism and grace. This module provides practical strategies for problem-solving, conflict resolution, and maintaining positive outcomes even in stressful circumstances.', NULL, 'content', 2, 25),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 3), 'Technology Tools & Platforms', 'Leverage technology to enhance your service delivery and efficiency. Explore the various digital tools, platforms, and software solutions that can streamline your work, improve communication, and provide better client experiences. Learn to integrate technology seamlessly into your workflow.', NULL, 'content', 3, 20),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 3), 'Communication Skills Assessment', 'Test your communication and service excellence knowledge and skills.', NULL, 'quiz', 4, 12);

-- Create subsections for Section 4: Specialized Relocations
INSERT INTO public.subsections (section_id, title, content, video_url, subsection_type, order_index, duration_minutes) VALUES
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 4), 'Corporate Relocations', 'Corporate relocations require specialized knowledge and handling. Learn the unique aspects of business-related moves including employee relocations, office moves, and corporate partnerships. Understand the additional considerations, stakeholders, and requirements that make corporate relocations distinct from residential moves.', NULL, 'content', 1, 30),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 4), 'International Moves', 'Navigate the complexities of international relocations with confidence. This comprehensive module covers customs regulations, international shipping, cultural considerations, and the unique challenges of cross-border moves. Learn to coordinate with international partners and ensure smooth global relocations.', NULL, 'content', 2, 35),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 4), 'Special Circumstances', 'Handle unique and challenging relocation scenarios including senior relocations, military moves, emergency situations, and clients with special needs. Develop the expertise to provide exceptional service regardless of the complexity or unusual nature of the relocation requirements.', NULL, 'content', 3, 28),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 4), 'Specialized Knowledge Assessment', 'Demonstrate your understanding of complex relocation scenarios and specialized services.', NULL, 'quiz', 4, 15);

-- Create subsections for Section 5: Professional Practice
INSERT INTO public.subsections (section_id, title, content, video_url, subsection_type, order_index, duration_minutes) VALUES
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 5), 'Ethics & Standards', 'Maintain the highest professional standards in all your relocation work. This module covers professional ethics, industry standards, and the code of conduct that governs exceptional relocation specialists. Learn how to navigate ethical dilemmas and always act in your clients'' best interests.', NULL, 'content', 1, 22),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 5), 'Continuing Education', 'Stay current with industry trends, regulations, and best practices through ongoing professional development. Discover resources for continuing education, industry certifications, and how to maintain your expertise as the relocation industry evolves.', NULL, 'content', 2, 18),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 5), 'Career Development', 'Plan and advance your career as a relocation specialist. Learn about different career paths, specializations, and opportunities for growth within the industry. Understand how to build your professional network, develop your personal brand, and achieve long-term success.', NULL, 'content', 3, 25),
((SELECT id FROM public.sections WHERE course_id = '686e9880-e7b9-464b-b5b9-d7632e211b0c' AND order_index = 5), 'Professional Practice Assessment', 'Final assessment covering professional ethics, standards, and career development principles.', NULL, 'quiz', 4, 20);